name: frontend
description: "SSAFY 자율프로젝트 C207"
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.1
  # recommend_screen
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

  # Search_Detail_Screen
  dashed_circular_progress_bar: ^0.0.6

  # Search_Camera_Screen
  camera: ^0.10.5+9
  scanner_overlay: ^0.0.2
  permission_handler: ^10.2.0
  image: ^3.0.1
  focused_area_ocr_flutter: ^0.0.3

  # for gallery image
  image_picker: ^1.1.0

  # for http request
  dio: ^5.4.3+1

  # for nation flag
  flag: ^7.0.0
  flutter_radar_chart: ^0.2.1

  #for common
  custom_rating_bar: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/aroma/

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter