spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  application:
    name: vinopener
  web:
    resources:
      add-mappings: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI:http://localhost:8080/auth/callback/google}
            profile-url: https://www.googleapis.com/userinfo/v2/me
            access-token-url: https://oauth2.googleapis.com/token
            authorization-code: authorization_code
  data:
    redis:
      host: ${REDIS_HOST:localhost}
#      # RedisRepository 사용하지 않는 경우 설정할 것
#      repositories:
#        enabled: false

server:
  forward-headers-strategy: framework

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  access-secret-key-base64: ${JWT_ACCESS_SECRET_KEY_BASE64:iAbBnFDrPJgglJr+yO0dC1qITxoCJcm1HB8ZiFWhtN19lWOdCaiPmvqXRTLmqe4cIdaT5X62swd/8lfp8rdw0Q==}
  access-expiration-seconds: ${JWT_ACCESS_EXPIRATION_SECONDS:300}
  #  access-expiration-seconds: ${JWT_ACCESS_EXPIRATION_SECONDS:2592000}
  refresh-secret-key-base64: ${JWT_REFRESH_SECRET_KEY_BASE64:zxY3hKXBd6MPmmxha1rwte7GayIdjuzOTeD6nyuO7MockdamStat6G0nDF2T8EJP041sdz4eZxEPNJEGIXGmiQ==}
  refresh-expiration-seconds: ${JWT_REFRESH_EXPIRATION_SECONDS:86400}

s3:
  access-key-id: ${S3_ACCESS_KEY_ID}
  secret-access-key: ${S3_SECRET_ACCESS_KEY}
  region: ${S3_REGION:ap-northeast-2}
  bucket: ${S3_BUCKET}
  endpoint: ${S3_ENDPOINT:}
  public-base-url: ${S3_PUBLIC_BASE_URL}

openai:
  api-key: ${OPENAI_API_KEY}
  organization-id: ${OPENAI_ORGANIZATION_ID}
  project-id: ${OPENAI_PROJECT_ID}

redis:
  ttl: 3600

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/vinopener
    username: ssafy
    password: ssafy

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST}/${MARIADB_DATABASE}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
